# sample recipe
apiVersion: v1
kind: generic-runner
meta:
  globalEnvVariable:
    REPLACE_RECIPE: true
    PIPELINE_LOG_DEBUG: false
    PIPELINE_INITIAL_ASSUME_ROLE: false
    RUN1: true
tasks:
  - condition: ${RUN1}
    script:
      ignoreErrors: false
      base64Encoded: false
      skip: false
      fileName: script.sh
      content: |
        echo "A normal case to test assume role and conditions"
        az account list --output table
