apiVersion: v2
name: helm-install
version: "1.0.0"
appVersion: "1.0.0"
description: helm-install
type: application
home: https://github.com/TIBCOSoftware/tp-helm-charts
maintainers:
  - name: TIBCO Cloud Dev Team
    email: cloud@tibco.com
